DROP TABLE IF EXISTS TRANSACTION_BANK_ACCOUNTS;

CREATE TABLE TRANSACTION_BANK_ACCOUNTS (
	ID_TRANS_BA serial PRIMARY KEY,
	BANK_ACCOUNT_NAME varchar (50) NOT NULL,
	BANK_ACCOUNT_DESC varchar (250) NULL,
	ACTIVE smallint NOT NULL default 1,
	INSERT_DATE timestamp default current_timestamp,
	UPDATE_DATE timestamp default current_timestamp
);
