DROP TABLE IF EXISTS TRANSACTION_BANK_ACCOUNTS CASCADE;

CREATE TABLE TRANSACTION_BANK_ACCOUNTS (
	ID_TRANS_BA serial PRIMARY KEY,
	ID_BA_OWN integer REFERENCES BANK_ACCOUNT_OWNER (ID_BA_OWN),
	ID_BA_TYP integer REFERENCES BANK_ACCOUNT_TYPES (ID_BA_TYP),
	BANK_ACCOUNT_NAME varchar (50) NOT NULL,
	BANK_ACCOUNT_DESC varchar (250) NULL,
	ACTIVE smallint NOT NULL default 1,
	INSERT_DATE timestamp default current_timestamp,
	UPDATE_DATE timestamp default current_timestamp
);
