CREATE TABLE TRANSACTION_CATEGORY (
	ID_TRANS_CAT serial PRIMARY KEY,
	CATEGORY_NAME varchar (50) NOT NULL,
	CATEGORY_DESCRIPTION varchar (250) NULL,
	ACTIVE smallint NOT NULL,
	INSERT_DATE date,
	UPDATE_DATE date
);
