CREATE TABLE TRANSACTION_TYPE (
	ID_TRANS_TYPE serial PRIMARY KEY,
	TRANSACTION_TYPE_NAME varchar (50) NOT NULL,
	TRANSACTION_TYPE_DESC varchar (250) NULL,
	ACTIVE smallint NOT NULL,
	INSERT_DATE date,
	UPDATE_DATE date
);
