CREATE TABLE TRANSACTION_SUBCATEGORY (
	ID_TRANS_SUBCAT serial PRIMARY KEY,
	ID_TRANS_CAT integer REFERENCES TRANSACTION_CATEGORY (ID_TRANS_CAT),
	SUBCATEGORY_NAME varchar (50) NOT NULL,
	SUBCATEGORY_DESCRIPTION varchar (250) NULL,
	ACTIVE smallint NOT NULL,
	INSERT_DATE date,
	UPDATE_DATE date
);

