DROP TABLE IF EXISTS TRANSACTION_SUBCATEGORY CASCADE;

CREATE TABLE TRANSACTION_SUBCATEGORY (
	ID_TRANS_SUBCAT serial PRIMARY KEY,
	ID_TRANS_CAT integer REFERENCES TRANSACTION_CATEGORY (ID_TRANS_CAT),
	SUBCATEGORY_NAME varchar (50) NOT NULL,
	SUBCATEGORY_DESCRIPTION varchar (250) NULL,
	ACTIVE smallint NOT NULL default 1,
	INSERT_DATE timestamp default current_timestamp,
	UPDATE_DATE timestamp default current_timestamp
);

