CREATE TABLE USERS (
 	ID_USER serial PRIMARY KEY,
	USER_LOGIN varchar (25) NOT NULL,
	USER_NAME varchar (50) NOT NULL,
	USER_PASSWORD varchar (100) NOT NULL,
	PASSWORD_SALT integer NOT NULL,
	ACTIVE smallint NOT NULL,
	INSERT_DATE date,
	UPDATE_DATE date
);
